In [1]:
import geopandas as gpd
import pandas as pd

In [6]:
intersections_geo = gpd.read_file('../../../../data/seattle/osm/osm-intersections/intersections-with-correct-geo/intersections-with-correct-geo.shp')
intersections_waytype = gpd.read_file('../../../../data/seattle/osm/osm-intersections/intersections-with-way-type/intersections-with-way-type.shp')

In [7]:
#spatial join two dataframes
df = gpd.sjoin(intersections_geo, intersections_waytype, how='inner')
df

,count_tota,geometry,index_right,highway,osmid,highway_2,osmid_2
0,24.0,POINT (-122.34375 47.66505),7370,residential,365394330,tertiary,8111778
1,10.0,POINT (-122.32027 47.69221),7233,residential,39276972,residential,984431792
2,10.0,POINT (-122.38639 47.67951),11257,residential,978885278,residential,978885279
3,72.0,POINT (-122.32675 47.61850),4457,tertiary,460423542,secondary,1136714996
4,48.0,POINT (-122.27696 47.52612),16572,tertiary,263732252,secondary,427898667
...,...,...,...,...,...,...,...
17618,56.0,POINT (-122.27705 47.52261),5338,residential,6345097,residential,6345097
17619,24.0,POINT (-122.30202 47.50604),11491,residential,165476746,residential,251562696
17620,16.0,POINT (-122.33322 47.54440),14160,unclassified,6437164,unclassified,6469825
17621,24.0,POINT (-122.31755 47.68602),10957,secondary,8591373,residential,6465997
17622,32.0,POINT (-122.24800 47.59011),17032,tertiary,344300175,tertiary,344300177

In [8]:
#keep highways osm_id and geometry from df
intersections = df[['highway','osmid', 'geometry']]
intersections

            highway      osmid                     geometry
0       residential  365394330  POINT (-122.34375 47.66505)
1       residential   39276972  POINT (-122.32027 47.69221)
2       residential  978885278  POINT (-122.38639 47.67951)
3          tertiary  460423542  POINT (-122.32675 47.61850)
4          tertiary  263732252  POINT (-122.27696 47.52612)
...             ...        ...                          ...
17618   residential    6345097  POINT (-122.27705 47.52261)
17619   residential  165476746  POINT (-122.30202 47.50604)
17620  unclassified    6437164  POINT (-122.33322 47.54440)
17621     secondary    8591373  POINT (-122.31755 47.68602)
17622      tertiary  344300175  POINT (-122.24800 47.59011)

[17611 rows x 3 columns]

In [ ]:
#save to shapefile
intersections.to_file('data/osm/osm-intersections/osm-intersections-cleaned/osm-intersections-cleaned.shp')